### ISSUE TITLE
I did what you tell us in README.md, but still have this error

### ISSUE THREAD

**Issue by Jasonyycyyc** [kkaren07/pytorch_pointpillars#1]
/usr/local/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr

1 error detected in the compilation of "/tmp/tmpxft_00002420_00000000-6_nms_kernel.cu.cpp1.ii".
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

You did really good work!!!!!! I hope if you have met this before and I'm very grateful to you!!!!!

**Comment by Jasonyycyyc** [comment]
> /usr/local/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00002420_00000000-6_nms_kernel.cu.cpp1.ii".
> concurrent.futures.process._RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in
> from second.core.non_max_suppression.nms import (
> ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'
> 
> During handling of the above exception, another exception occurred:
> 
> You did really good work!!!!!! I hope if you have met this before and I'm very grateful to you!!!!!

**Comment by Jasonyycyyc** [comment]
/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr 
/usr/local/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr

1 error detected in the compilation of "/tmp/tmpxft_000030cb_00000000-6_nms_kernel.cu.cpp1.ii".
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 13, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/utils/buildtools/command.py", line 255, in compile_func
    raise RuntimeError("compile failed with retcode", ret.returncode)
RuntimeError: ('compile failed with retcode', 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from second.builder import target_assigner_builder, voxel_builder
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/builder/target_assigner_builder.py", line 3, in <module>
    from second.core.target_assigner import TargetAssigner
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/target_assigner.py", line 1, in <module>
    from second.core import box_np_ops
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 21, in <module>
    cuda=True)
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/utils/buildtools/pybind11_build.py", line 113, in load_pb11
    cmds, cwd, num_workers=num_workers, compiler=compiler)
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/utils/buildtools/command.py", line 277, in compile_libraries
    if any([r.returncode != 0 for r in rets]):
  File "/home/lab1028/jason/pytorch_pointpillars-master/second.pytorch/second/utils/buildtools/command.py", line 277, in <listcomp>
    if any([r.returncode != 0 for r in rets]):
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/lab1028/anaconda3/envs/pointpillars/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: ('compile failed with retcode', 1)

**Comment by Jasonyycyyc** [comment]
I have solved the problem by

**Comment by Jasonyycyyc** [comment]
I have solved the problem by  change the  /second.pytorch/second/core/cc/nms/nms_kernel.cu.cc    //#include <boost/geometry.hpp>   Thanks very much for your code

**Comment by Jacksonfei** [comment]
> I have solved the problem by change the /second.pytorch/second/core/cc/nms/nms_kernel.cu.cc //#include <boost/geometry.hpp> Thanks very much for your code

could u tell me how to solve this problem?  i dont know how to deal with the nms_kernel.cu.cc

**Comment by Jasonyycyyc** [comment]
修饰掉//#include <boost/geometry.hpp>




On 03/11/2020 17:37, Donghui Ma wrote:

I have solved the problem by change the /second.pytorch/second/core/cc/nms/nms_kernel.cu.cc //#include <boost/geometry.hpp> Thanks very much for your code

could u tell me how to solve this problem? i dont know how to deal with the nms_kernel.cu.cc

**Comment by Jacksonfei** [comment]
> 修饰掉//#include <boost/geometry.hpp> On 03/11/2020 17:37, Donghui Ma wrote: I have solved the problem by change the /second.pytorch/second/core/cc/nms/nms_kernel.cu.cc //#include <boost/geometry.hpp> Thanks very much for your code could u tell me how to solve this problem? i dont know how to deal with the nms_kernel.cu.cc — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c: In function ‘void __device_stub__Z10nms_kernelIfLi64EEviT_PKS0_Py(int, float, const float*, long long unsigned int*)’:
/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c:11:148: error: ‘__args_arr’ was not declared in this scope
 ernelIfLi64EEviT_PKS0_Py(const int __par0, const float __par1, const float *__par2, unsigned long long *__par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 4UL);__cudaSetupArgSimple(__par2, 8UL);__cudaSetupArgSimple(__par3, 16UL);__cudaLaunch(((char *)((void ( *)(const int, const float, const float *, unsigned long long *))nms_kernel<float, (int)64> )));}
                                                                                                                 ^
/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c:11:148: error: ‘__args_idx’ was not declared in this scope
 ernelIfLi64EEviT_PKS0_Py(const int __par0, const float __par1, const float *__par2, unsigned long long *__par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 4UL);__cudaSetupArgSimple(__par2, 8UL);__cudaSetupArgSimple(__par3, 16UL);__cudaLaunch(((char *)((void ( *)(const int, const float, const float *, unsigned long long *))nms_kernel<float, (int)64> )));}
                                                                                                                 ^
/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c: In function ‘void __device_stub__Z10nms_kernelIdLi64EEviT_PKS0_Py(int, double, const double*, long long unsigned int*)’:
/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c:13:150: error: ‘__args_arr’ was not declared in this scope
 nelIdLi64EEviT_PKS0_Py(const int __par0, const double __par1, const double *__par2, unsigned long long *__par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(const int, const double, const double *, unsigned long long *))nms_kernel<double, (int)64> )));}
                                                                                                                 ^
/tmp/tmpxft_00002ff3_00000000-5_nms_kernel.cu.cudafe1.stub.c:13:150: error: ‘__args_idx’ was not declared in this scope
 nelIdLi64EEviT_PKS0_Py(const int __par0, const double __par1, const double *__par2, unsigned long long *__par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(const int, const double, const double *, unsigned long long *))nms_kernel<double, (int)64> )));}
                                                                                                                 ^
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mdh/lidar_SLAM_Algorithm/nutonomy_pointpillars/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
出现了新的错误。。。。

**Comment by Jacksonfei** [comment]
> 修饰掉//#include <boost/geometry.hpp> On 03/11/2020 17:37, Donghui Ma wrote: I have solved the problem by change the /second.pytorch/second/core/cc/nms/nms_kernel.cu.cc //#include <boost/geometry.hpp> Thanks very much for your code could u tell me how to solve this problem? i dont know how to deal with the nms_kernel.cu.cc — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

thank u! I have solved this problem.
